name: CI

on: ["pull", "push"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Gitleaks
        # Gitleaks configuration
      - name: Run OWASP Scanning
        # OWASP configuration
      - name: Run Trivy Scanning
        # Trivy configuration
